=== khedimyoucef/Languages-et-Outil-Web/TD2DTD/EXO1.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!-- note : it is recomended to start with simpler types -->
<!ELEMENT gare (train+,usager+) >
<!-- at least one element at most unbounded -->


<!ELEMENT train (voiture+, commentaire?)>
<!--  ? specifies that the comment can occur either 0 or 1 times inside train -->
<!ATTLIST train numero ID #REQUIRED>
<!ATTLIST train type CDATA #IMPLIED>


<!ELEMENT voiture (reservation* | buvette?)>
<!ATTLIST voiture numero CDATA #REQUIRED>
<!-- can't use ID since numero is of type string -->


<!ELEMENT reservation EMPTY>
<!-- EMPTY because the reservation element must not contain any child elements -->
<!-- attributes must be declared separately -->
<!ATTLIST reservation numero ID #REQUIRED>
<!ATTLIST reservation id IDREF #REQUIRED>

<!-- IDREF references to the usager that reserved it -->
<!ELEMENT buvette EMPTY>
<!ATTLIST buvette service CDATA #REQUIRED>


<!ELEMENT commentaire (#PCDATA,numero)>
<!ELEMENT numero (#PCDATA)>

<!-- the comment contains simple text + numero sub element -->


 
<!ELEMENT usager (prenom, nom, adresse, telephones?, emails?)>
<!-- the list of phones and emails is not required -->
<!ATTLIST usager id ID #REQUIRED>
<!-- id attribute name and the ID is the type of attribute named id  -->
    
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
    
<!ELEMENT adresse (rue, code_postal, ville, pays)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
    
<!ELEMENT telephones (telephone+)>
<!ELEMENT telephone (#PCDATA)>
<!-- can't use regular expressions (regex) to define the phone type hence the use of a string  -->
<!ATTLIST telephone type (fixe | mobile) #REQUIRED>
    
<!ELEMENT emails (email+)>
<!ELEMENT email (#PCDATA)>
<!-- same thing as the phone-->
<!ATTLIST email type (personnel | professionnel) #REQUIRED>

=== khedimyoucef/Languages-et-Outil-Web/TD2DTD/EXO1.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gare SYSTEM "EXO1.dtd">
<!-- or we can use <!DOCTYPE gare [gare.dtd code goes here]>   if the declaration of gare dtd is wanted to be internal--> 
<gare>
    <train numero="t5560" type="TGV">
        <voiture numero="v1">
            <reservation numero="r17" id="u55"/>
            <reservation numero="r18" id="u52"/>
        </voiture>
        <voiture numero="v2"/>
        <voiture numero="v3"/>
        <voiture numero="v4">
            <buvette service="froid uniquement"/>
        </voiture>
        <commentaire>Remplace l'ancien TGV <numero>t4215</numero></commentaire>
    </train>
    <train numero="t6731">
        <voiture numero="v1"/>
        <voiture numero="v2">
            <reservation numero="r15" id="u55"/>
        </voiture>s
    <usager id="u52">
        <prenom>Nihed</prenom>
        <nom>Mecheref</nom>
        <adresse>
            <rue>Rue 5 Juillet</rue>
            <code_postal>31000</code_postal>
            <ville>Oran</ville>
            <pays>Algérie</pays>
        </adresse>
        <telephones>
            <telephone type="fixe"> +213 (0) 48 .. .. .. </telephone>
            <telephone type="mobile"> +213 (0) 540 ... ... </telephone>
        </telephones>
        <emails>
            <email type="personnel">mohammed.ali@gmail.com</email>
            <email type="professionnel">m.ali@esi-sba.dz</email>
        </emails>
    </usager>
    <usager id="u55">
        <prenom>Mohamed</prenom>
        <nom>Salmi</nom>
        <!--suite declaration de l’usager u55… -->
    </usager>
</gare>
