=== khedimyoucef/Languages-et-Outil-Web/TD2XML/EXO3-3.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT entreprise (personnes, projets)>
    
<!ELEMENT personnes (personne*)>
<!ELEMENT personne (nom, informations)>
<!ATTLIST personne id_personne ID #REQUIRED projets_participes IDREFS #IMPLIED>

<!-- by using IDREFS we can directly specify the ids of the corresponding projects that the person contributed in using a list string attribute -->
<!ELEMENT nom (#PCDATA)>
<!ELEMENT informations (#PCDATA)>
    
<!ELEMENT projets (projet*)>
<!ELEMENT projet (nom, descriptif)>
<!ATTLIST projet id_projet ID #REQUIRED participants IDREFS #IMPLIED>

<!ELEMENT descriptif (#PCDATA)>

=== khedimyoucef/Languages-et-Outil-Web/TD2XML/EXO3-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entreprise SYSTEM "EXO3-3.dtd">
<entreprise>
    <personnes>
        <personne id_personne="p1" projets_participes="pr1">
            <nom>Omar</nom>
            <informations>Omar's info</informations>
        </personne>
        <personne id_personne="p2" projets_participes="pr1 pr2">
            <nom>Zohra</nom>
            <informations>Zohra's info</informations>
        </personne>
        <personne id_personne="p3" projets_participes="pr2">
            <nom>Mohamed</nom>
            <informations>MOhamed's infos</informations>
        </personne>
    </personnes>
    
    <projets>
        <projet id_projet="pr1" participants="p1 p2">
            <nom>Traduction</nom>
            <descriptif>Traduire certains elements de la documentation</descriptif>
        </projet>
        <projet id_projet="pr2" participants="p2 p3">
            <nom>Construction de corpus</nom>
            <descriptif>Rassembler et structurer toute la documentation</descriptif>
        </projet>
    </projets>
</entreprise>
