=== khedimyoucef/Languages-et-Outil-Web/TD2XML/EXO3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT entreprise (personnes, projets)>
    
<!ELEMENT personnes (personne*)>
<!ELEMENT personne (nom, informations, projets_participes)>
<!-- projet_participes is an array of empty elements where each subelement projet_participe is an empty element consisting of a reference id attribute -->
<!ATTLIST personne id_personne ID #REQUIRED>
            
<!ELEMENT nom (#PCDATA)>
<!ELEMENT informations (#PCDATA)>
<!ELEMENT projets_participes (projet_participe*)>
<!ELEMENT projet_participe EMPTY>

<!ATTLIST projet_participe id_projet IDREF #REQUIRED>
<!-- id_projet is an IDREF that refrences to the project that the person participates in  -->    
<!-- to keep track of the 1 person -> many projects relation -->
<!ELEMENT projets (projet*)>
<!ELEMENT projet (nom, descriptif, participants)>
<!ATTLIST projet id_projet ID #REQUIRED>
    
<!ELEMENT descriptif (#PCDATA)>
<!ELEMENT participants (participant+)>

<!ELEMENT participant EMPTY>
<!ATTLIST participant id_personne IDREF #REQUIRED>


<!-- to keep track of the 1 project -> many persons relation -->

=== khedimyoucef/Languages-et-Outil-Web/TD2XML/EXO3.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entreprise SYSTEM "EXO3.dtd">
<entreprise>
    <personnes>
        <personne id_personne="p1">
            <nom>Omar</nom>
            <informations>omar's info</informations>
            <projets_participes>
                <projet_participe id_projet="pr1"/>
            </projets_participes>
        </personne>
        <personne id_personne="p2">
            <nom>Zohra</nom>
            <informations>Zohra's info</informations>
            <projets_participes>
                <projet_participe id_projet="pr1"/>
                <projet_participe id_projet="pr2"/>
            </projets_participes>
        </personne>
        <personne id_personne="p3">
            <nom>Mohamed</nom>
            <informations>Mohamed's info</informations>
            <projets_participes>
                <projet_participe id_projet="pr2"/>
            </projets_participes>
        </personne>
    </personnes>

    <projets>
        <projet id_projet="pr1">
            <nom>Traduction</nom>
            <descriptif>Traduire certains elements de la documentation</descriptif>
            <participants>
                <participant id_personne="p1"/>
                <participant id_personne="p2"/>
            </participants>
        </projet>
        <projet id_projet="pr2">
            <nom>Construction de corpus</nom>
            <descriptif>Rassembler et structurer toute la documentation</descriptif>
            <participants>
                <participant id_personne="p2"/>
                <participant id_personne="p3"/>
            </participants>
        </projet>
    </projets>
</entreprise>
